### ISSUE TITLE
Mono headers on VitaSDK

### ISSUE THREAD

**Issue by fleimeris** [GrapheneCt/VitaMonoLoader#1]
I see that you are using Mono headers that are in VDS (SCE SDK):
https://github.com/GrapheneCt/VitaMonoLoader/blob/5a790d4fc986d2b29e5d6856c529e9f6c151e7a8/VitaMonoLoader/VitaMonoLoader.vcxproj#L48

but VitaSDK does not have any mono headers so it's impossible to compile. Could you assist with steps to compile loader with VitaSDK ?

**Comment by GrapheneCt** [comment]
These are not part of VDS, just generic mono headers that you can find anywhere. I'll add more info to the readme soon.

**Comment by GrapheneCt** [comment]
Added Mono headers to the repository.
